HZULibM/urls.py
from django.contrib import admin
from django.urls import path, include
import libFront.urls as FRONTURL
import libEnd.urls as ENDURL
from HZULibM import settings
from django.views.generic import RedirectView
from captcha.views import captcha_refresh
# from rest_framework import routers
from libFront.views import *
from django.conf.urls import url, static
# from rest_framework_jwt.views import obtain_jwt_token
# 验证码刷新功能，captcha_refresh为captcha.views内置方法，不需要我们单独写


# 前后端分离api的路由
# router = routers.DefaultRouter()
# router.register(r'libBook', BookViewSet)
# router.register(r'libCategory', CategoryViewSet)
# router.register(r'libUser', UserViewSet)
# router.register(r'libBookFavourite', BooklikeViewSet)
# router.register(r'libBookCollection', BookCollectionViewSet)
# router.register(r'libComment', CommentViewSet)
# router.register(r'libCommentFavourite', CommentlikeViewSet)
# router.register(r'libBack', BackViewSet)
# router.register(r'libMessage', MessageViewSet)
# router.register(r'libAnnouncement', AnnouncementViewSet)
# router.register(r'libConfirmString', ConfirmStringViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lf/', include(FRONTURL)),
    path('captcha/', include('captcha.urls')),
    path('lm/', include(ENDURL)),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/picture/favicon.ico')),
    path('refresh/', captcha_refresh),
    path('', include(FRONTURL)),

    # path('api/',include(router.urls)),
]

libEnd/urls.py
from django.urls import path

from . import views

app_name = "lm"

urlpatterns = [
    path('', views.index, name="index"),

    path('user/ul', views.userlist, name="userlist"),
    path('user/uahl', views.authoritylist, name="authoritylist"),
    path('user/upl', views.userrepsdlist, name="userrepsdlist"),
    path('user/ud/<int:id>', views.userdetail, name="userdetail"),

    path('book/bl', views.booklist, name="booklist"),
    path('book/bd/<int:id>', views.bookdetail, name="bookdetail"),
    path('book/bc/<int:id>', views.bookcomment, name="bookcomments"),
    path('book/catgs', views.bookcategorys, name="bookcategorys"),
    path('book/catg/<int:id>', views.bookcategory, name="bookcategory"),

    path('bb/borrow', views.borrowlist, name="borrowlist"),
    path('bb/back', views.backlist, name="backlist"),
    path('bb/bbdetail/<int:type>/<int:id>', views.bbdetail, name="bbdetail"),
    path('bb/badborrow', views.badborrow, name="badborrow"),

    path('oth/ann', views.announcement, name="announcement"),
    path('oth/bcc', views.commentconfirm, name="commentconfirm"),
    path('oth/msg', views.messages, name="messages"),

    path('operation', views.operation, name="operation"),

    path("user/search/<str:kw>", views.usersearch, name="usersearch"),
    path("book/search/<str:kw>", views.booksearch, name="booksearch"),

    path('api', views._api)
]

libFront/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
# from rest_framework_jwt.views import obtain_jwt_token
app_name = "libfront"
urlpatterns = [
    path('', views.login),
    path('login', views.login, name="login"),
    path('index',views.index,name="index"),
    path('logout', views.logout, name="logout"),
    path('register', views.register, name="register"),
    path('user/<int:id>', views.userdetail, name="userdetail"),
    path('book/<int:bookid>', views.bookdetail, name="bookdetail"),
    path('rank/<str:st>/<int:pg>', views.ranklist, name="ranklist"),
    path('category/<int:categid>/<int:pg>', views.categorylist, name="category"),
    path('categorys', views.categorys, name="categorys"),
    path('book/borrow', views.borrow_ajax, name="borrow"),
    path('book/back', views.back_ajax, name="back"),
    path('search/<str:kw>/<int:pg>', views.search, name="search"),
    path('operation', views.operation),
    path('confirm/', views.user_confirm),



    #前后端分离api接口
    # url(r'^authorization/$',obtain_jwt_token),
    # url(r'^api/v1/$',views.AuthView.as_view()),
    # url(r'^api/v2/$',views.OrderView.as_view()),
]

libFront/forms.py
from captcha.fields import CaptchaField
from django import forms
# django的form组件
#用来校验用户提交的数据
class loginForm(forms.Form):
    account = forms.CharField(label="账号", max_length=128, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "超级管理员账号s,密码1", 'autofocus': '', 'value': 's'}))
    password = forms.CharField(label="密码", max_length=256,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "1", 'value': '1'}))
    captcha = CaptchaField(label='验证码')

libFront/views.py
import hashlib
from datetime import timedelta

from django.conf import settings
from django.db.models import Q, Sum
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from Utils.decorators import *
from Utils.redis_lrucache import *
# from LibM.scripts.decorators import *
# from LibM.scripts.redis_lrucache import *
from libEnd import views as ENDVIEW
from .forms import *
from .models import *

def login(request):
    if request.method == "GET":
        lgf = loginForm()
        return render(request, "login.html", locals())

    lgf = loginForm(request.POST)
    if not lgf.is_valid():# 进行数据校验
        #校验失败
        msg = "验证码错误，请重新输入！"
        return render(request, "login.html", locals())

    account = request.POST.get("account")
    password = request.POST.get("password")
    user_login_type = request.POST.get("user_login_type")
    user = libUser.objects.filter(account=account, password=password)

    if user.count() == 0:
        msg = "账号或密码错误，请检查。"
        return render(request, "login.html", locals())

    user = user[0]

    if not user.has_confirmed:
        msg = "账号尚未进行邮箱验证，请前往邮箱验证后再登陆。"
        return render(request, "login.html", locals())

    # 设置过期时间
    request.session.set_expiry(settings.SESSION_EXPIRE_TIME)
    #会话保持
    request.session.__setitem__("has_login", True)#标记过期未结束
    request.session.__setitem__("user_id", user.id)
    request.session.__setitem__("account", user.account)
    request.session.__setitem__("nickname", user.nickname)
    request.session.__setitem__("user_type", user.type)
    if user.change_password_required:
        request.session.__setitem__("change_password_required", user.change_password_required)

    data = {
        "l_time": datetime.now(),
    }
    libUser.objects.update(**data)

    # 判断是否有权限进入后台
    if user_login_type == "r":
        if user.type == 1 or user.type == 0:
            return ENDVIEW.index(request)
        else:
            request.session.clear()
            msg = "非管理员账号，无法登入后台。"
            return render(request, "login.html", locals())
    else:
        return redirect(reverse("libfront:index"))

def index(request):
    print("loading index")
    books = libBook.objects.all()
    newest = books.order_by("-c_time")[:15]#排行
    newest2 = books.order_by("-c_time")[:5]#速递
    scorehighest = books.order_by("-score")[:15]
    commentest = books.order_by("-comment_num")[:15]
    recommends = books.order_by("?")[:8]
    list1 = libCategory.objects.all()[0].libbook_set.all().select_related()[:5]
    list2 = libCategory.objects.all()[1].libbook_set.all().select_related()[:5]
    list3 = libCategory.objects.all()[2].libbook_set.all().select_related()[:5]
    list4 = libCategory.objects.all()[3].libbook_set.all().select_related()[:5]
    cms = libComment.objects.filter(has_confirmed=True).order_by('-p_num').select_related()[:5]
    msg = libAnnouncement.objects.filter(
        Q(type=request.session.get("user_type", "-1")) | Q(type=3)
        | Q(for_user_id=request.session.get("user_id", "-1"))
    ).filter(c_time__gte=datetime.now() - timedelta(days=7))
    msgnum = msg.count()
    msg = {"msg": msg, "msgnum": msgnum}
    userid = request.session.get("user_id", -1)

    return render(request, "index.html", locals())

def categorylist(request, categid, pg):
    ONE_PAGE_ITEM_NUM = 15
    cat = libCategory.objects.get(id=categid)
    books = cat.libbook_set.all()
    all_num = int(books.count() / ONE_PAGE_ITEM_NUM) + (1 if books.count() % ONE_PAGE_ITEM_NUM != 0 else 0)
    rmds = books.order_by("-score")[:ONE_PAGE_ITEM_NUM]
    books = books.select_related()[(pg - 1) * ONE_PAGE_ITEM_NUM:(pg - 1) * ONE_PAGE_ITEM_NUM + ONE_PAGE_ITEM_NUM]
    return render(request, "category.html", locals())

def ranklist(request, st, pg):
    ONE_PAGE_ITEM_NUM = 15
    st = "-" + st
    books = libBook.objects.all()
    all_num = int(books.count() / ONE_PAGE_ITEM_NUM) + (1 if books.count() % ONE_PAGE_ITEM_NUM != 0 else 0)
    qs = books.order_by(st)[(pg - 1) * ONE_PAGE_ITEM_NUM:(pg - 1) * ONE_PAGE_ITEM_NUM + ONE_PAGE_ITEM_NUM]
    return render(request, "ranklist.html", locals())


def bookdetail(request, bookid):
    book = libBook.objects.get(id=bookid)
    catgs = book.categ.all()[:3]
    if len(catgs) > 0:
        catg = catgs[0]
    chapters = book.chapters.split(",")
    rmds = libBook.objects.all().order_by("-score")[:10]
    cms = book.libcomment_set.filter(has_confirmed=True).order_by("-c_time").select_related()
    cmsnum = book.libcomment_set.filter(has_confirmed=True).count()
    userid = request.session.get("user_id", -1)
    return render(request, "bookdetail.html", locals())


@login_required_json
def borrow_ajax(request):
    u_id = request.POST.get("user_id")
    b_id = request.POST.get("book_id")
    endtime = request.POST.get("endtime")
    print(111)
    print(endtime)
    user = get_object_or_404(libUser, id=u_id)
    book = get_object_or_404(libBook, id=b_id)
    data = {
        "code": 200,
    }
    if book.stock_now <= 0:
        data['code'] = 401
    else:
        # try:
        borrow = libBorrow()
        borrow.user = user
        borrow.book = book
        borrow.c_time = datetime.now()
        print(endtime)
        borrow.p_time = endtime + " 23:59:00"
        borrow.save()
        libBook.objects.filter(id=b_id).update(stock_now=book.stock_now - 1, borrow_num=book.borrow_num + 1)
        # except :
        #     data['code'] = 400


    return JsonResponse(data)


def logout(request):
    request.session.clear()
    try:
        CACHE.delete("lfindex(){}")
    except:
        pass
    return redirect(reverse("libfront:index"))
    # return index(request)

def hash_code(s, salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


def make_confirm_string(user):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.account, now)
    return code


def send_email(email, code):
    host_name = "127.0.0.1:8000"
    from django.core.mail import EmailMultiAlternatives
    subject = '来自贺院云书苑的注册确认邮件'

    text_content = '''感谢注册贺院云书苑，\
                    如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''

    html_content = '''
                    <p>感谢注册<a href="http://{}/lf/confirm/?code={}" target=blank>贺院云书苑</a>。</p>
                    <p>请点击站点链接完成注册确认！</p>
                    <p>此链接有效期为{}天！</p>
                    <p>唯君不思，无我不为。祝你在书苑有一个良好的体验。</p>
                    '''.format(host_name, code, settings.EMAIL_CONFIRM_EXPIRE_TIME)
    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


def register(request):
    global msg
    if request.method == "GET":
        return render(request, "register.html",locals())

    typ = 1

    account = request.POST.get("account")
    same_account_user_count = libUser.objects.filter(account=account).count()
    if same_account_user_count != 0:
        msg = "用户名重复"

    email = request.POST.get("email")
    same_email_user_account = libUser.objects.filter(email=email).count()
    if same_account_user_count != 0:
        msg += "邮箱重复"

    psd = request.POST.get("password")
    nickname = request.POST.get("nickname")
    gender = request.POST.get("gender")
    birthday = request.POST.get("birthday")
    description = request.POST.get("description")

    if same_account_user_count + same_account_user_count != 0:
        return render(request, "register.html", {'msg': msg})

    user = libUser()
    user.nickname = nickname
    user.account = account
    user.password = psd
    user.email = email
    user.gender = gender
    user.birthday = birthday
    user.description = description

    user.save()
    code = make_confirm_string(user)
    libConfirmString.objects.create(user=user, code=code)
    send_email(email, code)
    lgf = loginForm()
    msg = "成功注册，请前往邮箱进行验证后进行登陆。"

    return render(request, "login.html", {'msg': msg, 'lgf': lgf})


#@cache_it_httpresponse(prefix="lf", expiration=10)
@login_required
def userdetail(request, id):
    user = libUser.objects.filter(id=request.session.get("user_id"))[0]

    borrow = libBorrow.objects.select_related().filter(user=user).order_by('-c_time')
    borrow = {"borrow": borrow, "borrownum": borrow.count()}

    back = libBack.objects.select_related().filter(user=user)
    back = {"back": back, "backnum": back.count()}

    comments = libComment.objects.select_related().filter(user=user)
    comments = {"comments": comments, "commentsnum": comments.count()}

    collection = libBookCollection.objects.select_related().filter(user=user)
    collection = {"collection": collection, "collectionnum": collection.count()}

    msg = libAnnouncement.objects.filter(
        Q(type=request.session.get("user_type", "-1")) | Q(type=3)
        | Q(for_user_id=request.session.get("user_id", "-1"))
    ).filter(c_time__gte=datetime.now() - timedelta(days=7))
    msg = {"msg": msg, "msgnum": msg.count()}

    firenum = libComment.objects.filter(user_id=request.session.get("user_id")).aggregate(Sum('p_num'))['p_num__sum']
    if firenum is None:
        firenum = 0
    print(type(firenum))
    print(firenum)
    return render(request, "userdetail.html", locals())


#@cache_it_httpresponse(60 * 60 * 24, prefix="lf")
def categorys(request):
    catgs = libCategory.objects.all()
    return render(request, "categorys.html", locals())


#@cache_it_httpresponse(prefix="lf")
def search(request, kw, pg):
    ONE_PAGE_ITEM_NUM = 15
    books = libBook.objects.filter(Q(name__icontains=kw) | Q(author__icontains=kw) | Q(publisher__icontains=kw))
    all_num = int(books.count() / ONE_PAGE_ITEM_NUM) + (1 if books.count() % ONE_PAGE_ITEM_NUM != 0 else 0)
    rmds = books.order_by("-score")[:ONE_PAGE_ITEM_NUM]
    books = books.select_related()[(pg - 1) * ONE_PAGE_ITEM_NUM:(pg - 1) * ONE_PAGE_ITEM_NUM + ONE_PAGE_ITEM_NUM]

libFront/templates/headerbar-back.html
{% load static %}


<div class="navbar navbar-inverse">
    <div class="container">

        <div class="navbar-header">
            <a href="{% url "libfront:index" %}" class="navbar-brand logo" title="书苑">
                书苑
            </a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation" id="nav-header">

            <ul class="nav navbar-nav">
                <li><a href="{% url "libfront:category" 64 1 %}">学习资源</a></li>
                <li><a href="{% url "libfront:category" 65 1 %}">名著</a></li>
                <li><a href="{% url "libfront:category" 66 1 %}">小说</a></li>
                <li><a href="{% url "libfront:category" 67 1 %}">历史</a></li>
                <li><a href="{% url "libfront:category" 68 1 %}">报刊杂志</a></li>
                <li><a href="{% url "libfront:category" 69 1 %}">科技</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">语言<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url "libfront:category" 70 1 %}">日语</a></li>
                        <li><a href="{% url "libfront:category" 71 1 %}">英语</a></li>
                        <li><a href="{% url "libfront:category" 72 1 %}">韩语</a></li>
                        <li><a href="{% url "libfront:categorys" %}">全部分类</a></li>
                    </ul>
                </li>
                <li class="dropdown"><a class="dropdown-toggle"
                                        data-toggle="dropdown">排行榜<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url "libfront:ranklist" "score" 1 %}">评分榜</a></li>
                        <li><a href="{% url "libfront:ranklist" "comment_num" 1 %}">评论榜</a></li>
                        <li><a href="{% url "libfront:ranklist" "c_time" 1 %}">最新入库</a></li>
                    </ul>
                </li>
                <li><a href="/admin">Admin</a></li>
                <li><a href="/lm">BACKNED</a></li>
                <li><a href="#" onclick="hideall()">欣赏壁纸</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.has_login %}
                    {# 已登陆则显示头像下拉框 #}
                    <li class="dropdown"><a class="dropdown-toggle" href="javascript:;" data-toggle="dropdown"><i
                            class="fa fa-user fa-fw"></i>{{ request.session.nickname }}<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url "libfront:userdetail"  request.session.user_id %}" title="个人资料">
                                <i class="fa fa-info fa-fw"></i>个人资料</a>
                            </li>
                            <li>
                                <a href="{% url "libfront:userdetail"  request.session.user_id %}" title="站内消息">
                                    <i class="fa fa-envelope fa-fw"></i>站内消息</a>
                            </li>
                            <li><a href="{% url "libfront:logout" %}" title="退出登录">
                                <i class="fa fa-power-off fa-fw"></i>退出登录</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    {#未登陆则显示注册登陆按钮#}
                    <li><a id="loginbtn" href="{% url "libfront:login" %}">登陆</a></li>
                    <li><a id="registerbtn" href="{% url "libfront:register" %}">注册</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="clear"></div>
{% if request.session.change_password_required %}

    <div class="alert alert-warning text-center">
        管理员通知：请及时更改密码，更改密码前无法使用本账号。</br>
        <p id="idontknow">
            <span id="time">3</span>
            秒后自动
            <a href="{% url "libfront:userdetail" request.session.user_id %}">跳转</a>
            ,若无反应请手动点击。
        </p>
    </div>

    <script type="text/javascript">
        var count = 3;
        url = window.location.pathname;
        burl = "/user/" + {{ request.session.user_id }};
        console.log(url === burl);

        //一开始就执行
        if (url !== burl) {
            window.setInterval("refresh()", 1000);
        } else {
            document.getElementById("idontknow").style.display = "None";
        }

        function refresh() {
            if (count > 1) {
                //修改span中的数字
                count -= 1;
                document.getElementById("time").innerText = count;
            } else {
                location.href = "{% url "libfront:userdetail" request.session.user_id %}";
            }
        }
    </script>
{% endif %}

libFront/templates/headerbar.html
{% load static %}
<style>
    html{
		overflow-x: hidden;
	}
	.box-top{
		height: 200px;
		background: url({% static 'picture/index/03.png' %}) center center / cover no-repeat;
		color: #FFFFFF;
	}
	.box-top img{
		width: 200px;
	}
	.search-box{
	    position: absolute;
	    top: 100px;
	    left: 700px;
	    display: block;
	}
	.search-box .searchClass{
	  border: 1px solid #c5c5c5;
	  border-radius: 20px;
	  background: #f4f4f4;
      width: 500px;
      color: #333333;
	}
	.search-box .searchicno{
        font-size: 17px;
        margin: 0px 3px;
	}
	.searchClass:hover{
	  border: 1px solid #D5E3E8;
	  background: #fff;
	}
</style>
{% include 'bgimg.html' %}
<div class="could-hide">
    <div class="box-top">
        <img src="{% static 'picture/index/02.png' %}"/>
        <div class="search-box">
                <input type="search" class="searchClass"/>
                <span class="searchicno lfsbtn shbtn"><i class="fa fa-search"></i></span>
        </div>
    </div>
    <div class="navbar navbar-inverse">
        <div class="container">

            <div class="navbar-header">
                <a href="{% url 'libfront:index' %}" class="navbar-brand logo" title="书苑">
                    书苑
                </a>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation" id="nav-header">
                <ul class="nav navbar-nav" id="ulbar">
                    <li id="headurl" class="hidden">{% url "libfront:category" 1 1 %}</li>
                    <li class="fake-li"><a>冒险</a></li>
                    <li class="fake-li"><a>惊悚</a></li>
                    <li class="fake-li"><a>考古</a></li>
                    <li class="fake-li"><a>天文</a></li>
                    <li class="fake-li"><a>心理</a></li>
                    <li class="fake-li"><a>美学</a></li>
                    <li class="fake-li"><a>法律</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">语言<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu" id="dropdownbar">

                        </ul>
                    </li>

                    <li class="dropdown"><a class="dropdown-toggle"
                                            data-toggle="dropdown">排行榜<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'libfront:ranklist' 'score' 1 %}">评分榜</a></li>
                            <li><a href="{% url 'libfront:ranklist' 'comment_num' 1 %}">评论榜</a></li>
                            <li><a href="{% url 'libfront:ranklist' 'c_time' 1 %}">最新入库</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'libfront:categorys' %}">全部分类</a></li>
                    {% if request.session.user_type == 1 %}
                    <li><a href="{% url 'lm:index' %}">秘密基地</a></li>
                    {% endif %}
                    {% if request.session.user_type == 0 %}
                    <li><a href="{% url 'lm:index' %}">秘密基地</a></li>
                    {% endif %}
                    {#                <li><a href="/admin">Admin</a></li>#}
                    {#                <li><a href="/lm">BACKNED</a></li>#}
                    {#                <li><a href="#" onclick="hideall()">欣赏壁纸</a></li>#}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.session.has_login %}
                        {# 已登录则显示头像下拉框 #}
                        <li class="dropdown"><a class="dropdown-toggle" href="javascript:;" data-toggle="dropdown"><i
                                class="fa fa-user fa-fw"></i>{{ request.session.nickname }}<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'libfront:userdetail'  request.session.user_id %}">
                                    <i class="fa fa-info fa-fw"></i>个人资料</a>
                                </li>

                                <li>
                                    <a href="{% url 'libfront:logout' %}">
                                        <i class="fa fa-power-off fa-fw"></i>退出登录
                                    </a>
                                </li>
                                {#                            {% if request.session.user_type != 2 %}#}
                                {#                                <li>#}
                                {#                                    <a href="{% url 'libfront:logout' %}">#}
                                {#                                        <i class="fa fa-power-off fa-fw"></i>退出登录#}
                                {#                                    </a>#}
                                {#                                </li>#}
                                {#                            {% endif %}#}
                            </ul>
                        </li>
                    {% else %}
                        {#未登录则显示注册登录按钮#}
                        <li><a id="loginbtn" href="{% url 'libfront:login' %}">登录/注册</a></li>

                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
<script type="text/javascript">
function loadheaderbar() {
    $.ajax({
        url: "/lf/operation",
        method: "POST",
        data: {
            operation: "load_headerbar"
        },
        success: function (data) {
            var catg1 = data["catg1"],
                catg2 = data["catg2"],
                href = $("#headurl").text();
            console.log(catg1)
            var html1 = "",
                html2 = "";
            for (var i = 0; i < catg1.length; i++) {
                var name = catg1[i][0], id = catg1[i][1];
                html1 += '<li><a href="' + href.substring(0, href.length - 3) + id + '/1">' + name + "</a></li>";
            }
            $(".fake-li").hide();
            $("#ulbar").prepend(html1);
            for (var i = 0; i < catg2.length; i++) {
                var name = catg2[i][0], id = catg2[i][1];
                html2 += '<li><a href="' + href.substring(0, href.length - 3) + id + '/1">' + name + "</a></li>";
            }
            $("#dropdownbar").prepend(html2);
        },
        error: function () {

        }
    })
}
loadheaderbar()
</script>
<div class="clear"></div>

{% if request.session.change_password_required %}

    <div class="alert alert-warning text-center">
        管理员通知：请及时更改密码，更改密码前无法使用本账号。</br>
        <p id="idontknow">
            <span id="time">3</span>
            秒后自动
            <a href="{% url 'libfront:userdetail' request.session.user_id %}">跳转</a>
            ,若无反应请手动点击。
        </p>
    </div>

    <script type="text/javascript">
        var count = 3;
        url = window.location.pathname;
        burl = "/user/" + {{ request.session.user_id }};
        console.log(url === burl);

        //一开始就执行
        if (url !== burl) {
            window.setInterval("refresh()", 1000);
        } else {
            document.getElementById("idontknow").style.display = "None";
        }

        function refresh() {
            if (count > 1) {
                //修改span中的数字
                count -= 1;
                document.getElementById("time").innerText = count;
            } else {
                location.href = "{% url "libfront:userdetail" request.session.user_id %}";
            }
        }
    </script>
{% endif %}


<script>
    var has_login = false;
    {% if request.session.has_login %}
        has_login = true;
    {% endif %}

<!--    var lastTime = new Date().getTime();-->
<!--    var currentTime = new Date().getTime();-->
<!--    var expiretime = 1000 * 10;//过期时间设置-->

<!--    $(function () {-->
<!--        /* 鼠标移动事件 更新上次操作时间 */-->
<!--        $(document).mouseover(function () {-->
<!--            lastTime = new Date().getTime();-->
<!--        });-->
<!--    });-->

<!--    function autoLogout() {-->
<!--        if (has_login) {-->
<!--            currentTime = new Date().getTime();-->
<!--            if (currentTime - lastTime > expiretime) {-->
<!--                alert("检测到连续%s秒无动作，即将自动退出".replace("%s", expiretime / 1000));-->
<!--                has_login = false;-->
<!--                window.location.replace("/lf/logout");-->
<!--            }-->
<!--        }-->
<!--    }-->

<!--    /* 定时器-->
<!--     * 间隔1秒检测是否长时间未操作页面-->
<!--     */-->
<!--    window.setInterval(autoLogout, 1000);-->
</script>