HZULibM/urls.py
from django.contrib import admin
from django.urls import path, include
import libFront.urls as FRONTURL
import libEnd.urls as ENDURL
from HZULibM import settings
from django.views.generic import RedirectView
from captcha.views import captcha_refresh
# from rest_framework import routers
from libFront.views import *
from django.conf.urls import url, static
# from rest_framework_jwt.views import obtain_jwt_token
# 验证码刷新功能，captcha_refresh为captcha.views内置方法，不需要我们单独写


# 前后端分离api的路由
# router = routers.DefaultRouter()
# router.register(r'libBook', BookViewSet)
# router.register(r'libCategory', CategoryViewSet)
# router.register(r'libUser', UserViewSet)
# router.register(r'libBookFavourite', BooklikeViewSet)
# router.register(r'libBookCollection', BookCollectionViewSet)
# router.register(r'libComment', CommentViewSet)
# router.register(r'libCommentFavourite', CommentlikeViewSet)
# router.register(r'libBack', BackViewSet)
# router.register(r'libMessage', MessageViewSet)
# router.register(r'libAnnouncement', AnnouncementViewSet)
# router.register(r'libConfirmString', ConfirmStringViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lf/', include(FRONTURL)),
    path('captcha/', include('captcha.urls')),
    path('lm/', include(ENDURL)),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/picture/favicon.ico')),
    path('refresh/', captcha_refresh),
    path('', include(FRONTURL)),

    # path('api/',include(router.urls)),
]

libEnd/urls.py
from django.urls import path

from . import views

app_name = "lm"

urlpatterns = [
    path('', views.index, name="index"),

    path('user/ul', views.userlist, name="userlist"),
    path('user/uahl', views.authoritylist, name="authoritylist"),
    path('user/upl', views.userrepsdlist, name="userrepsdlist"),
    path('user/ud/<int:id>', views.userdetail, name="userdetail"),

    path('book/bl', views.booklist, name="booklist"),
    path('book/bd/<int:id>', views.bookdetail, name="bookdetail"),
    path('book/bc/<int:id>', views.bookcomment, name="bookcomments"),
    path('book/catgs', views.bookcategorys, name="bookcategorys"),
    path('book/catg/<int:id>', views.bookcategory, name="bookcategory"),

    path('bb/borrow', views.borrowlist, name="borrowlist"),
    path('bb/back', views.backlist, name="backlist"),
    path('bb/bbdetail/<int:type>/<int:id>', views.bbdetail, name="bbdetail"),
    path('bb/badborrow', views.badborrow, name="badborrow"),

    path('oth/ann', views.announcement, name="announcement"),
    path('oth/bcc', views.commentconfirm, name="commentconfirm"),
    path('oth/msg', views.messages, name="messages"),

    path('operation', views.operation, name="operation"),

    path("user/search/<str:kw>", views.usersearch, name="usersearch"),
    path("book/search/<str:kw>", views.booksearch, name="booksearch"),

    path('api', views._api)
]

libEnd/models.py
from django.db import models

# Create your models here.

libEnd/views.py
import datetime

from django.core import serializers
from django.db.models import Q
from django.utils.timezone import now

from Utils.decorators import *
from Utils.redis_lrucache import *
# from LibM.scripts.decorators import *
# from LibM.scripts.redis_lrucache import *
from libFront import models as md
from libFront.templatetags.mytemplate import timediff


# Create your views here.


def getUnreadedNews():
    msgss = md.libMessage.objects.filter(readed=False).order_by("-c_time")
    msgs = msgss[:6]
    msgnum = msgss.count()
    return msgs, msgnum


@auth_administrator_required
@login_required
def index(request):
    website_title = "书苑-后台"
    page_title = "主页"
    messages, msgnum = getUnreadedNews()

    uc = md.libUser.objects.all().count()
    bc = md.libBook.objects.all().count()
    brc = md.libBorrow.objects.all().filter(p_time__lt=now()).count()
    ccc = md.libComment.objects.filter(has_confirmed=False).count()

    return render(request, "libEnd/index.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def userlist(request):
    website_title = "用户管理"
    page_title = "用户信息"
    messages, msgnum = getUnreadedNews()

    one_page_item_num = 10
    page = 1
    if request.method == "POST":
        one_page_item_num = int(request.POST.get("one_page_item_num", 10))
        page = int(request.POST.get("page", 1))

    page -= 1
    start = page * one_page_item_num + 1
    end = page * one_page_item_num + one_page_item_num
    users = md.libUser.objects.exclude(id=request.session.get("user_id")).order_by("-c_time")[start - 1:end]
    obj_num = md.libUser.objects.all().count()
    page_num = int(round(obj_num / one_page_item_num + 0.49))
    return render(request, "libEnd/userlist.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def booklist(request):
    website_title = "书籍管理"
    page_title = "书籍信息"
    messages, msgnum = getUnreadedNews()

    one_page_item_num = 10
    page = 1
    if request.method == "POST":
        one_page_item_num = int(request.POST.get("one_page_item_num", 10))
        page = int(request.POST.get("page", 1))

    page -= 1
    start = page * one_page_item_num + 1
    end = page * one_page_item_num + one_page_item_num

    books = md.libBook.objects.all().order_by("-c_time")[start - 1:end]

    obj_num = md.libBook.objects.all().count()
    page_num = int(round(obj_num / one_page_item_num + 0.49))
    return render(request, "libEnd/booklist.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def messages(request):
    website_title = "书苑-留言板"
    page_title = "留言板"
    messages, msgnum = getUnreadedNews()

    messages_all = md.libMessage.objects.all().order_by("-c_time")
    return render(request, "libEnd/messages.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def userdetail(request, id):
    website_title = "用户管理"
    page_title = "新建用户"
    messages, msgnum = getUnreadedNews()

    if id != 0:
        page_title = "用户详细资料"
        user = md.libUser.objects.filter(id=id)[0]
    return render(request, "libEnd/userdetail.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def authoritylist(request):
    website_title = "用户管理"
    page_title = "管理员设置"
    messages, msgnum = getUnreadedNews()

    one_page_item_num = 10
    page = 1
    if request.method == "POST":
        one_page_item_num = int(request.POST.get("one_page_item_num", 10))
        page = int(request.POST.get("page", 1))

    page -= 1
    start = page * one_page_item_num + 1
    end = page * one_page_item_num + one_page_item_num
    users = md.libUser.objects.filter(type__in=[0, 1])[start - 1:end]
    obj_num = md.libUser.objects.all().count()
    page_num = int(round(obj_num / one_page_item_num + 0.49))
    return render(request, "libEnd/userlist.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def userrepsdlist(request):
    website_title = "用户管理"
    page_title = "待更改密码用户列表"
    messages, msgnum = getUnreadedNews()

    users = md.libUser.objects.all().filter(change_password_required=True)[: 10]
    return render(request, "libEnd/userlist.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def usersearch(request, kw):
    website_title = "用户管理"
    page_title = "搜索结果 - " + kw
    messages, msgnum = getUnreadedNews()

    ob = md.libUser.objects.all().filter(
        Q(nickname__icontains=kw) | Q(account__icontains=kw) | Q(description__icontains=kw))

    one_page_item_num = 10
    page = 1
    if request.method == "POST":
        one_page_item_num = int(request.POST.get("one_page_item_num", 10))
        page = int(request.POST.get("page", 1))

    page -= 1
    start = page * one_page_item_num + 1
    end = page * one_page_item_num + one_page_item_num
    users = ob[start - 1:end]
    obj_num = ob.count()
    page_num = int(round(obj_num / one_page_item_num + 0.49))

    return render(request, "libEnd/userlist.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def booksearch(request, kw):
    website_title = "书籍管理"
    page_title = "搜索结果 - " + kw
    messages, msgnum = getUnreadedNews()

    ob = md.libBook.objects.all().filter(
        Q(name__icontains=kw) | Q(author__icontains=kw) | Q(description__icontains=kw) | Q(publisher__icontains=kw))

    one_page_item_num = 10
    page = 1
    if request.method == "POST":
        one_page_item_num = int(request.POST.get("one_page_item_num", 10))
        page = int(request.POST.get("page", 1))

    page -= 1
    start = page * one_page_item_num + 1
    end = page * one_page_item_num + one_page_item_num
    books = ob[start - 1:end]
    obj_num = ob.count()
    page_num = int(round(obj_num / one_page_item_num + 0.49))
    return render(request, "libEnd/booklist.html", locals())


#@cache_it_httpresponse(10, prefix="lm")
def bookdetail(request, id):
    website_title = "书籍管理"
    page_title = "新建书籍"
    messages, msgnum = getUnreadedNews()
    catgs = md.libCategory.objects.all()

    if id != 0:
        page_title = "书籍详细信息"
        book = md.libBook.objects.select_related().filter(id=id)[0]
    return render(request, "libEnd/bookdetail.html", locals())


#@cache_it_httpresponse(60 * 10)
def bookcategory(request, id):
    cat = md.libCategory.objects.get(id=id)
    website_title = "书籍管理"
    page_title = "分类 - " + cat.name
    messages, msgnum = getUnreadedNews()

    ob = cat.libbook_set.all().order_by('-p_num')

    one_page_item_num = 10
    page = 1
    if request.method == "POST":
        one_page_item_num = int(request.POST.get("one_page_item_num", 10))
        page = int(request.POST.get("page", 1))

    page -= 1
    start = page * one_page_item_num + 1
    end = page * one_page_item_num + one_page_item_num
    books = ob[start - 1:end]
    obj_num = ob.count()
    page_num = int(round(obj_num / one_page_item_num + 0.49))
    return render(request, "libEnd/booklist.html", locals())


@auth_administrator_required_json
@login_required_json
def operation(request):
    if request.method == "GET":
        return HttpResponse(json.dumps({}))

    global catgs, ob
    data = request.POST.dict()
    # print(data)
    obj = request.POST.get("object")
    op = request.POST.get("operation")
    id = request.POST.get("id", 0)

    typ = request.POST.get("type", "1")
    if obj == "book":
        ob = md.libBook
    elif obj == "user":
        ob = md.libUser
    elif obj == "bb":
        if typ == "1" or typ == "3":
            ob = md.libBorrow
        else:
            ob = md.libBack
    elif obj == "message":
        ob = md.libMessage
    elif obj == "comment":
        ob = md.libComment
    elif obj == "announcement":
        ob = md.libAnnouncement

    if id != 0:
        del data['id']
    del data['object']
    del data['operation']
    keys = data.keys()
    # print(data)
    if obj == "user":
        if "l_time" in keys:
            data['l_time'] = data['l_time'][:10] + " " + data["l_time"][11:] + ":00"
        if "c_time" in keys:
            data['c_time'] = data['c_time'][:10] + " " + data["c_time"][11:] + ":00"
    elif obj == "bb":
        if "c_time" in keys:
            data['c_time'] = data['c_time'][:10] + " " + data["c_time"][11:] + ":00"
        if "p_time" in keys:
            data['p_time'] = data['p_time'][:10] + " " + data["p_time"][11:] + ":00"
        if "f_time" in keys:
            if len(data['f_time']) > 5:
                data['f_time'] = data['f_time'][:10] + " " + data["f_time"][11:] + ":00"
            else:
                del data['f_time']
        del data['type']

    # print(data)
    res = {"code": 200}

    # print(data)
    if op == "delete":
        res['msg'] = "删除成功"
        ob.objects.filter(id=id).delete()
    elif op == "update":
        res['msg'] = "信息更改成功"
        ob.objects.filter(id=id).update(**data)
    elif op == "change_password_required":
        res['msg'] = "操作成功"
        user = ob.objects.get(id=id)
        if user.change_password_required == False:
            ob.objects.filter(id=id).update(change_password_required=True)
        else:
            ob.objects.filter(id=id).update(change_password_required=False)
    elif op == "pass":
        res['msg'] = "操作成功"
        if ob.objects.filter(id=id)[0].has_confirmed:
            ob.objects.filter(id=id).update(has_confirmed=False)
        else:
            ob.objects.filter(id=id).update(has_confirmed=True)
    elif op == "create":
        res['msg'] = "创建成功"
        if obj == "book":
            data['stock_now'] = data['stock_all']
        cob = ob.objects.create(**data)
    elif op == "back_book_required":
        res['msg'] = "操作成功"
        lb = ob.objects.get(id=id)
        bookname = lb.book.name
        tf = timediff(lb.p_time, datetime.datetime.now())
        msg = "您在{}借的书《{}》超时未归还(约定于{})，目前已逾期{}".format(
            lb.c_time.strftime("%Y-%m-%d %H:%M"), bookname,
            lb.p_time.strftime("%Y-%m-%d %H:%M"), tf)
        md.libAnnouncement.objects.create(from_user=md.libUser.objects.get(id=request.session.get("user_id")),

libEnd/templates/libEnd/bblist.html
{% extends "libEnd/template.html" %}
{% load mytemplate %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">用户信息</h3>
                    <p style="display: None" id="type">{{ type }}</p>
                    <div class="float-right">
                        <a class="btn bg-primary">
                            <i class="fas fa-edit"></i>
                        </a>编 辑
                        <a class="btn btn-danger">
                            X
                        </a>删 除
                        {% if type == 3 %}
                            <a class="btn btn-danger">
                                <i class="fas fa-notes-medical"></i>
                            </a>通知还书
                        {% endif %}
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                <div class="dataTables_length"><label>Show
                                    <select name="one_page_item_num"
                                            class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="10"
                                                {% if one_page_item_num == 10 %}selected="selected"{% endif %}>10
                                        </option>
                                        <option value="25"
                                                {% if one_page_item_num == 25 %}selected="selected"{% endif %}>25
                                        </option>
                                        <option value="50"
                                                {% if one_page_item_num == 50 %}selected="selected"{% endif %}>50
                                        </option>
                                        <option value="100"
                                                {% if one_page_item_num == 100 %}selected="selected"{% endif %}>100
                                        </option>
                                    </select> entries</label></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1"
                                       class="table table-bordered table-striped dataTable dtr-inline"
                                       role="grid" aria-describedby="example1_info">
                                    <thead>
                                    <tr role="row">
                                        <th rowspan="1" colspan="1"> 书籍</th>
                                        <th rowspan="1" colspan="1"> 用户</th>
                                        <th rowspan="1" colspan="1"> 起始时间</th>
                                        <th rowspan="1" colspan="1"> 约定还书时间</th>
                                        {% if type == 2 %}
                                            <th rowspan="1" colspan="1"> 最终还书时间</th>
                                        {% elif type == 3 %}
                                            <th rowspan="1" colspan="1"> 已逾期</th>
                                        {% endif %}
                                        <th rowspan="1" colspan="1"> 操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for bo in bbs %}
                                        <tr class="{% if forloop.counter == 0 or forloop.counter == 2 or forloop.counter == 4 or forloop.counter == 6 or forloop.counter == 8 %}odd{% else %}even{% endif %}">
                                            <td style="display: None">{{ bo.id }}</td>
                                            <td><a href="{% url "lm:bookdetail" bo.book.id %}">{{ bo.book }}</a></td>
                                            <td><a href="{% url "lm:userdetail" bo.user.id %}">{{ bo.user }}</a></td>
                                            <td>{{ bo.c_time }}</td>
                                            <td>{{ bo.p_time }}</td>
                                            {% if type == 2 %}
                                                <td>{{ bo.f_time }}</td>
                                            {% elif type == 3 %}
                                                <td>{% timediff end=bo.p_time %}</td>
                                            {% endif %}
                                            <td>
                                                {# 1 借 2 还 3 逾期#}
                                                <a class="btn bg-primary"
                                                   href="{% if type == 1 or type == 3 %}{% url "lm:bbdetail" 1 bo.id %}
                                                   {% else %}{% url "lm:bbdetail" 2 bo.id %}{% endif %}">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-danger bbde">
                                                    X
                                                </a>
                                                {% if type == 3 %}
                                                    <a class="btn btn-danger bbrd">
                                                        <i class="fas fa-notes-medical"></i>
                                                    </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}


                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1"> 书籍</th>
                                        <th rowspan="1" colspan="1"> 用户</th>
                                        <th rowspan="1" colspan="1"> 起始时间</th>
                                        <th rowspan="1" colspan="1"> 约定还书时间</th>
                                        {% if type == 2 %}
                                            <th rowspan="1" colspan="1"> 最终还书时间</th>
                                        {% elif type == 3 %}
                                            <th rowspan="1" colspan="1"> 已逾期</th>
                                        {% endif %}
                                        <th rowspan="1" colspan="1"> 操作</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        {% include "libEnd/table_page.html" %}
                    </div>
                </div>
                <!-- /.card-body -->
            </div>

        </div>

    </div>
{% endblock %}


{% block footer %}
    <script>
        generatePageNum({{ page }}, {{ page_num }});
        $(".page-link").click(function () {
            var url = window.location.pathname;
            var one_page_item_num = $("[name=one_page_item_num]").val();
            var pg = $(this).text();
            var token = $.cookie("csrftoken");
            console.log(one_page_item_num);
            console.log(pg);
            data = {
                'object': 'book',
                'one_page_item_num': one_page_item_num,
                'page': pg,
                "X-CSRFToken": token,
            };
            postToNewTabWithJSONByjQuery(url, data);
            window.opener = null;
            window.open('', '_self');
            window.close();
        });
    </script>
{% endblock %}

libEnd/templates/libEnd/bookcategorys.html
{% extends "libEnd/template.html" %}
{% load mytemplate %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% for cat,bknum in catgs %}
                {% judgeline forloop.counter 4 0 %}

                <div class="col-md-3">
                    <div class="info-box">
                    <span class="info-box-icon {% randcatgbg %}">
                        <i class="far fa-bookmark"></i>
                    </span>
                        <a href="{% url "lm:bookcategory" cat.id %}">
                            <div class="info-box-content">
                                <span class="info-box-text">{{ cat.name }}</span>
                                <span class="info-box-number">书籍数量：{{ bknum }}</span>
                            </div>
                        </a>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>

                {% if forloop.last or forloop.counter|judgeline_filter:4 %}
                    </div>
                {% endif %}
            {% endfor %}
    </div>
    </div>
{% endblock %}

libEnd/templates/libEnd/booklist.html
{% extends "libEnd/template.html" %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">用户信息</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                <div class="dataTables_length"><label>Show
                                    <select name="one_page_item_num"
                                            class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="10"
                                                {% if one_page_item_num == 10 %}selected="selected"{% endif %}>10
                                        </option>
                                        <option value="25"
                                                {% if one_page_item_num == 25 %}selected="selected"{% endif %}>25
                                        </option>
                                        <option value="50"
                                                {% if one_page_item_num == 50 %}selected="selected"{% endif %}>50
                                        </option>
                                        <option value="100"
                                                {% if one_page_item_num == 100 %}selected="selected"{% endif %}>100
                                        </option>
                                    </select> entries</label></div>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <div class="dataTables_filter">
                                    <label>Search:</label>
                                    <input type="search" class="form-control">&nbsp;&nbsp;
                                    <button class="btn btn-default bsh lmrsbtn">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1"
                                       class="table table-bordered table-striped dataTable dtr-inline"
                                       role="grid" aria-describedby="example1_info">
                                    <thead>
                                    <tr role="row">
                                        <th rowspan="1" colspan="1"> 书名</th>
                                        <th rowspan="1" colspan="1"> 作者</th>
                                        <th rowspan="1" colspan="1"> 出版社</th>
                                        <th rowspan="1" colspan="1"> 出版日期</th>
                                        <th rowspan="1" colspan="1"> 分类</th>
                                        <th rowspan="1" colspan="1"> 总库存</th>
                                        <th rowspan="1" colspan="1"> 当前库存</th>
                                        <th rowspan="1" colspan="1"> 操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for book in books %}
                                        <tr class="{% if forloop.counter == 0 or forloop.counter == 2 or forloop.counter == 4 or forloop.counter == 6 or forloop.counter == 8 %}odd{% else %}even{% endif %}">
                                            <td style="display: None">{{ book.id }}</td>
                                            <td><a href="{% url "lm:bookdetail" book.id %}">{{ book.name }}</a></td>
                                            <td>
                                                <a href="{% url "lm:booksearch" book.author %}">
                                                    {{ book.author }}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url "lm:booksearch" book.publisher %}">
                                                    {{ book.publisher }}
                                                </a>
                                            </td>
                                            <td>{{ book.pubdate }}</td>
                                            <td>
                                                {% for tag in book.categ.all %}
                                                    <a class="cm-tag"
                                                       href="{% url "lm:bookcategory" tag.id %}">{{ tag }}</a>
                                                {% endfor %}
                                            </td>
                                            <td>{{ book.stock_all }}</td>
                                            <td>{{ book.stock_now }}</td>
                                            <td>
                                                <a class="btn bg-primary"
                                                   href="{% url "lm:bookdetail" book.id %}">编辑</a>
                                                <a class="btn bg-danger bde">删除</a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th rowspan="1" colspan="1"> 书名</th>
                                        <th rowspan="1" colspan="1"> 作者</th>
                                        <th rowspan="1" colspan="1"> 出版社</th>
                                        <th rowspan="1" colspan="1"> 出版日期</th>
                                        <th rowspan="1" colspan="1"> 分类</th>
                                        <th rowspan="1" colspan="1"> 总库存</th>
                                        <th rowspan="1" colspan="1"> 当前库存</th>
                                        <th rowspan="1" colspan="1"> 操作</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        {% include "libEnd/table_page.html" %}
                    </div>
                </div>
                <!-- /.card-body -->
            </div>

        </div>

    </div>

{% endblock %}

{% block footer %}
    <script>
        generatePageNum({{ page }}, {{ page_num }});
        $(".page-link").click(function () {
            var url = window.location.pathname;
            var one_page_item_num = $("[name=one_page_item_num]").val();
            var pg = $(this).text();
            var token = $.cookie("csrftoken");
            console.log(one_page_item_num);
            console.log(pg);
            data = {
                'object': 'book',
                'one_page_item_num': one_page_item_num,
                'page': pg,
                "X-CSRFToken": token,
            };
            postToNewTabWithJSONByjQuery(url, data);
            window.opener = null;
            window.open('', '_self');
            window.close();
        });
    </script>
{% endblock %}

libEnd/templates/libEnd/commentconfirm.html
{% extends "libEnd/template.html" %}
{% load  static %}
{% block content %}
    <div class="timeline">
        <!-- Timeline time label -->
        <div class="time-label">
            <span class="bg-green">{% now "Y-m-d" %}</span>
        </div>

        <!-- Before each timeline item corresponds to one icon on the left scale -->

        <!-- Timeline item -->
        {% for cmt in comments %}
            <div>
                <p style="display: None" class="cid">{{ cmt.id }}</p>
                <i class="fas fa-comment bg-blue"></i>
                <div class="timeline-item">
                    <!-- Time -->
                    <span class="time"><i class="fas fa-clock"></i> {{ cmt.c_time }}</span>
                    <!-- Header. Optional -->
                    <h3 class="timeline-header">
                        To
                        <a href="{% url "lm:bookdetail" cmt.book.id %}">{{ cmt.book.name }}</a>
                        By
                        <a href="{% url "lm:userdetail" cmt.user.id %}">{{ cmt.user.nickname }}</a>
                    </h3>
                    <!-- Body -->
                    <div class="timeline-body">
                        {{ cmt.comment }}
                    </div>
                    <!-- Placement of additional controls. Optional -->
                    <div class="timeline-footer">
                        <a class="btn btn-primary btn-sm cps">通过</a>
                        <a class="btn btn-danger btn-sm cfl">拒绝</a>
                    </div>
                </div>
            </div>
        {% endfor %}

        <!-- The last icon means the story is complete -->
        <div>
            <i class="fas fa-clock bg-gray"></i>
        </div>
    </div>
{% endblock %}